export const BAHT = '฿' as const

export const menuCategory = [
  'Drink', 'Soft drinks - beer - whisky', 'Breakfast',
  'Rice dishes', 'Stir-fried', 'Curry soup',
  'Burger, Sandwich, Pizza', 'Soup', 'Salad',
  'Spicy Thai salad', 'Noodle dishes', 'B.B.Q',
  'Spaghetti & Macaroni', 'Snacks',
] as const

export type MenuCategory = typeof menuCategory[number]

// MenuCategory, Description, price, image base name
export type MenuItem = [MenuCategory, string, number, string]

const menu: MenuItem[] = [
  ['Drink', 'Hot tea, coffee, ovaltine', 30, ''],
  ['Drink', 'Hot lemon tea, chinese tea, lemongrass tea, ginger tea', 30, ''],
  ['Drink', 'Ice tie, coffee, ovaltine', 60, ''],
  ['Drink', 'Orange, lemon, pineapple, watermelon juice', 60, ''],
  ['Drink', 'Carrot juice', 60, ''],
  ['Drink', 'Mixed fruit juice', 60, ''],
  ['Drink', 'Coffee, ovaltine shake', 60, ''],
  ['Drink', 'Banana, pineapple, mango, coconut, strawberry, orange, lemon, watermelon shake', 60, ''],
  ['Drink', 'Mixed fruit shake', 60, ''],
  ['Drink', 'Carrot shake', 60, ''],
  ['Drink', 'Strawberry youghurt shake', 70, ''],
  ['Drink', 'Youghurt fruit shake', 70, ''],
  ['Drink', 'Fresh coconut', 60, ''],
  ['Soft drinks - beer - whisky', 'Water small', 15, ''],
  ['Soft drinks - beer - whisky', 'Water large', 30, ''],
  ['Soft drinks - beer - whisky', 'Coke', 30, ''],
  ['Soft drinks - beer - whisky', 'Sprite', 30, ''],
  ['Soft drinks - beer - whisky', 'Fanta (orange, strawberry)', 30, ''],
  ['Soft drinks - beer - whisky', 'Schweppes', 40, ''],
  ['Soft drinks - beer - whisky', 'Fresh coconut', 60, ''],
  ['Soft drinks - beer - whisky', 'Singha beer (small)', 60, ''],
  ['Soft drinks - beer - whisky', 'Singha beer (large)', 90, ''],
  ['Soft drinks - beer - whisky', 'Leo beer (small)', 60, ''],
  ['Soft drinks - beer - whisky', 'Chang beer (small)', 60, ''],
  ['Soft drinks - beer - whisky', 'Chang beer (large)', 80, ''],
  ['Soft drinks - beer - whisky', 'Vodka red bull', 150, ''],
  ['Soft drinks - beer - whisky', 'Vodka lemon', 150, ''],
  ['Soft drinks - beer - whisky', 'Vodka orange', 150, ''],
  ['Soft drinks - beer - whisky', 'Vodka coke', 150, ''],
  ['Soft drinks - beer - whisky', 'Vodka sprite', 150, ''],
  ['Soft drinks - beer - whisky', 'Gin tonic', 150, ''],
  ['Soft drinks - beer - whisky', 'Piña colada', 150, ''],
  ['Soft drinks - beer - whisky', 'Mai Tai', 150, ''],
  ['Soft drinks - beer - whisky', 'Tequila sunrise', 150, ''],
  ['Breakfast', 'English breakfast (bacon, eggs, baked beans, sausage, toast)', 160, ''],
  ['Breakfast', 'American breakfast (coffee or tea or ovaltine, fruit salad or juice, bacon, eggs, toast)', 160, ''],
  ['Breakfast', 'Plain toast', 40, ''],
  ['Breakfast', 'Toast with butter, jam or honey', 70, ''],
  ['Breakfast', 'Toast with peanut butter', 70, ''],
  ['Breakfast', 'Baked beans on toast', 80, ''],
  ['Breakfast', 'Friend\'s toast with lemon, honey, sweet milk', 80, ''],
  ['Breakfast', 'Fried eggs on toast', 80, ''],
  ['Breakfast', 'Poached eggs on toast', 80, ''],
  ['Breakfast', 'Boiled eggs with toast', 80, ''],
  ['Breakfast', 'Scrambled eggs with toast', 80, ''],
  ['Breakfast', 'Garlic bread', 80, ''],
  ['Breakfast', 'Plain omelette', 70, ''],
  ['Breakfast', 'Omelette with chicken, pork', 80, ''],
  ['Breakfast', 'Cheese omelette', 80, ''],
  ['Breakfast', 'Cheese tomato toast', 80, ''],
  ['Breakfast', 'Tuna tomato toast', 80, ''],
  ['Breakfast', 'Ham cheese toast', 80, ''],
  ['Breakfast', 'Porridge with milk', 70, ''],
  ['Breakfast', 'Porridge with banana, pineapple', 80, ''],
  ['Breakfast', 'Fruit salad', 80, ''],
  ['Breakfast', 'Pancake with banana, pineapple', 80, ''],
  ['Breakfast', 'Banana in warm coconut milk', 80, ''],
  ['Breakfast', 'Muesli youghurt with fruit', 80, ''],
  ['Breakfast', 'Corn flakes with milk and fruit', 80, ''],
  ['Breakfast', 'Rice soup with pork, chicken', 80, ''],
  ['Rice dishes', 'Steamed rice', 30, ''],
  ['Rice dishes', 'Fried eggs with rice', 80, ''],
  ['Rice dishes', 'Omelette with rice', 80, ''],
  ['Rice dishes', 'Fried rice with garlic', 80, ''],
  ['Rice dishes', 'Fried rice with vegetable and eggs', 80, 'fried-rice-w-vegetable-and-egg'],
  ['Rice dishes', 'Fried rice with vegetable chicken, pork, seafood', 90, ''],
  ['Rice dishes', 'Fried rice with pineapple chicken, pork, seafood', 90, ''],
  ['Rice dishes', 'Fried rice with vegetable tuna and eggs', 100, ''],
  ['Rice dishes', 'Fried rice with vegetable seafood and eggs', 100, ''],
  ['Rice dishes', 'Fried rice with garlic chicken, pork, seafood', 90, ''],
  ['Rice dishes', 'Spicy fried rice with chicken, pork, seafood', 90, ''],
  ['Rice dishes', 'Fried rice with cashew nuts chicken, pork, seafood', 100, ''],
  ['Rice dishes', 'Fried chicken, pork, seafood with garlic and pepper on rice', 100, 'garlic-pepper-chicken'],
  ['Rice dishes', 'Fried Thai curry with chicken, pork, seafood, tofu on rice', 90, ''],
  ['Rice dishes', 'Fried Thai curry beef on rice', 100, ''],
  ['Rice dishes', 'Fried chicken, pork, seafood with chilli and & basil leaves on rice', 90, ''],
  ['Stir-fried', 'Stir-fried vegetable', 90, ''],
  ['Stir-fried', 'Stir-fried vegetable with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried sweet & sour vegetable with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried baby corn with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried pineapple with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried thai curry potato', 100, ''],
  ['Stir-fried', 'Stir-fried bean sprout with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried cashew nuts with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried mushroom with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried mixed vegetable oyster sauce with chicken, pork, seafood, tofu', 100, ''],
  ['Stir-fried', 'Stir-fried mixed vegetable oyster sauce with beef', 120, ''],
  ['Stir-fried', 'Stir-fried massaman curry with chicken, pork, seafood, tofu', 100, 'massaman-curry-chicken'],
  ['Stir-fried', 'Stir-fried panang curry with chicken, pork, seafood, tofu', 100, ''],
  ['Curry soup', 'Vegetable clear soup', 90, ''],
  ['Curry soup', 'Vegetable clear soup with chicken, pork, seafood, tofu', 100, ''],
  ['Curry soup', 'Tom yam with chicken, pork, shrimp, seafood, tofu', 100, 'tom-yam-shrimp'],
  ['Curry soup', 'Yellow curry with pineapple and tuna', 100, ''],
  ['Curry soup', 'Thai curry soup with chicken, pork, seafood, tofu', 100, ''],
  ['Curry soup', 'Thai curry soup pineapple with chicken, pork, seafood, tofu', 100, ''],
  ['Curry soup', 'Green curry soup with chicken, pork, seafood, tofu', 100, 'green-curry-chicken'],
  ['Curry soup', 'Gang garee with chicken, pork, seafood, tofu', 100, ''],
  ['Curry soup', 'Coconut soup with chicken, pork, seafood, tofu', 100, ''],
  ['Curry soup', 'Coconut soup lemon grass with chicken, pork, seafood, tofu', 100, ''],
  ['Curry soup', 'Tom yam coconut soup with lemongrass chicken, pork, seafood, tofu', 100, ''],
  ['Burger, Sandwich, Pizza', 'Tuna burger', 90, ''],
  ['Burger, Sandwich, Pizza', 'Burger with chicken, pork', 90, ''],
  ['Burger, Sandwich, Pizza', 'Chicken baguette', 90, ''],
  ['Burger, Sandwich, Pizza', 'Tuna baguette', 90, ''],
  ['Burger, Sandwich, Pizza', 'Tuna sandwich', 90, ''],
  ['Burger, Sandwich, Pizza', 'Cheese sandwich', 90, ''],
  ['Burger, Sandwich, Pizza', 'Cheese baguette', 90, ''],
  ['Burger, Sandwich, Pizza', 'Eggs sandwich', 90, ''],
  ['Burger, Sandwich, Pizza', 'Bacon baguette', 90, ''],
  ['Burger, Sandwich, Pizza', 'Cheese burger with beef', 90, ''],
  ['Burger, Sandwich, Pizza', 'Chicken cheese baguette', 90, ''],
  ['Burger, Sandwich, Pizza', 'Cheese burger with french fries', 150, ''],
  ['Burger, Sandwich, Pizza', 'Pizza with vegetable', 150, ''],
  ['Burger, Sandwich, Pizza', 'Pizza with vegetable and tuna', 200, ''],
  ['Burger, Sandwich, Pizza', 'Pizza Hawaii', 200, ''],
  ['Burger, Sandwich, Pizza', 'Pizza with vegetable chicken, seafood', 200, ''],
  ['Soup', 'Mushroom', 80, ''],
  ['Soup', 'Tomato soup', 80, ''],
  ['Soup', 'Onion soup', 80, ''],
  ['Soup', 'Sweet corn soup', 80, ''],
  ['Salad', 'Mix vegetable salad', 90, ''],
  ['Salad', 'Tomato salad', 90, ''],
  ['Salad', 'Tuna salad', 100, ''],
  ['Salad', 'Potato salad', 100, ''],
  ['Salad', 'Eggs salad', 100, ''],
  ['Salad', 'Chicken salad', 100, ''],
  ['Salad', 'Seafood salad', 100, ''],
  ['Spicy Thai salad', 'Thai style tuna in tomato sauce salad', 90, ''],
  ['Spicy Thai salad', 'Papaya salad (som tum)', 90, ''],
  ['Spicy Thai salad', 'Vegetable thai salad', 100, ''],
  ['Spicy Thai salad', 'Spicy glass noodle with chicken, pork', 150, ''],
  ['Spicy Thai salad', 'Spicy seafood salad', 150, ''],
  ['Spicy Thai salad', 'Spicy pork salad', 150, ''],
  ['Spicy Thai salad', 'Spicy fried cashew nuts chicken salad', 200, ''],
  ['Spicy Thai salad', 'Spicy squid salad', 150, ''],
  ['Spicy Thai salad', 'Spicy prawn salad', 150, ''],
  ['Noodle dishes', 'Pad thai noodle with eggs', 90, ''],
  ['Noodle dishes', 'Pad thai noodle vegetable chicken, pork, seafood, tofu', 100, ''],
  ['Noodle dishes', 'Fried noodle with vegetable & eggs', 90, 'noodles-w-vegetable-and-egg'],
  ['Noodle dishes', 'Fried noodle with chicken, pork, seafood, tofu', 100, ''],
  ['Noodle dishes', '(Mama) fried yellow noodle with chicken, pork, seafood, tofu', 100, ''],
  ['Noodle dishes', 'Fried glass noodle with chicken, pork, seafood, tofu', 100, ''],
  ['Noodle dishes', 'Radna vegetable with chicken, pork, seafood, tofu', 100, ''],
  ['Noodle dishes', 'Noodle soup vegetable with chicken, pork, seafood, tofu', 100, ''],
  ['Noodle dishes', 'Sour and spicy noodle soup vegetable with chicken, pork, seafood, tofu', 90, ''],
  ['Noodle dishes', '(Mama) eggs noodle with chicken, pork, seafood, tofu', 90, ''],
  ['B.B.Q', 'B.B.Q fish, chicken, pork, seafood with garlic & pineapple', 250, ''],
  ['B.B.Q', 'B.B.Q fish, chicken, pork with ginger', 250, ''],
  ['B.B.Q', 'Fried fish with garlic & pepper', 250, 'garlic-pepper-fish'],
  ['B.B.Q', 'Deep fried fish with sweet & sour sauce', 250, ''],
  ['B.B.Q', 'Fried fish in curry', 250, ''],
  ['B.B.Q', 'Steam fish with lemon', 250, ''],
  ['B.B.Q', 'Pork with honey', 250, ''],
  ['B.B.Q', 'Tandoori with chicken', 250, ''],
  ['B.B.Q', 'Fried prawn in thai curry sauce', 250, ''],
  ['Spaghetti & Macaroni', 'Macaroni cheese', 90, ''],
  ['Spaghetti & Macaroni', 'Spaghetti cheese', 90, ''],
  ['Spaghetti & Macaroni', 'Spaghetti & tomato sauce', 90, ''],
  ['Spaghetti & Macaroni', 'Spaghetti bolognese', 100, ''],
  ['Spaghetti & Macaroni', 'Spaghetti carbonara', 100, ''],
  ['Spaghetti & Macaroni', 'Spaghetti tuna', 100, ''],
  ['Spaghetti & Macaroni', 'Fried macaroni with vegetable, chicken, pork, seafood', 100, ''],
  ['Snacks', 'Mash potato', 90, ''],
  ['Snacks', 'No name vegetable', 90, ''],
  ['Snacks', 'No name with chicken, pork, seafood', 100, ''],
  ['Snacks', 'Crispy fried vegetable', 100, ''],
  ['Snacks', 'Thai potato fritter', 100, ''],
  ['Snacks', 'Banana fritter', 100, ''],
  ['Snacks', 'Pineapple fritter', 100, ''],
  ['Snacks', 'Spring rolls', 100, ''],
  ['Snacks', 'Onion ring', 100, ''],
  ['Snacks', 'Prawns crackers', 100, ''],
  ['Snacks', 'French fried', 100, ''],
  ['Snacks', 'Fried prawns batter', 200, ''],
  ['Snacks', 'Fried chicken batter', 200, 'fried-chicken'],
  ['Snacks', 'Chicken and chips', 200, ''],
  ['Snacks', 'Fish and chips', 200, ''],
  ['Snacks', 'Calamari', 200, ''],
]

export default menu
